split docker build as 0-step

diff --git a/.github/workflows/phpunit.yml b/.github/workflows/phpunit.yml
--- a/.github/workflows/phpunit.yml
+++ b/.github/workflows/phpunit.yml
@@ -8,7 +8,34 @@ permissions:
   contents: read
 
 jobs:
+  build-containers:
+    runs-on: ubuntu-latest
+    if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
+    timeout-minutes: 10
+    steps:
+      - uses: actions/checkout@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v2
+
+      - name: Cache Docker php-image
+        id: docker-php-image-cache
+        uses: actions/cache@v3
+        with:
+          path: /tmp/docker-save
+          key: ${{ runner.os }}-docker-php-build-save-${{ hashFiles('**/Dockerfile.php.common', '**/Dockerfile.php74') }}
+      - run: docker load -i /tmp/docker-save/snapshot.tar || true
+        if: steps.docker-php-image-cache.outputs.cache-hit == 'true'
+      - run: ls -l && docker build -f build/Dockerfile.php74 -t app/php-image --cache-from=app/php-image-cache ./build
+        if: steps.docker-php-image-cache.outputs.cache-hit != 'true'
+        env:
+          DOCKER_BUILDKIT: '1'
+          COMPOSE_DOCKER_CLI_BUILD: '1'
+      - run: docker tag app/php-image app/php-image-cache && mkdir -p /tmp/docker-save && docker save app/php-image-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
+        if: always() && steps.docker-php-image-cache.outputs.cache-hit != 'true'
+
   build:
+    needs: build-containers
     runs-on: ubuntu-latest
     if: "!contains(github.event.head_commit.message, 'skip-github-actions')"
     timeout-minutes: 10
@@ -27,13 +54,8 @@ jobs:
         key: ${{ runner.os }}-docker-php-build-save-${{ hashFiles('**/Dockerfile.php.common', '**/Dockerfile.php74') }}
     - run: docker load -i /tmp/docker-save/snapshot.tar || true
       if: steps.docker-php-image-cache.outputs.cache-hit == 'true'
-    - run: ls -l && docker build -f build/Dockerfile.php74 -t app/php-image --cache-from=app/php-image-cache ./build
+    - run: echo 'Failed to fetch cache' && exit 1
       if: steps.docker-php-image-cache.outputs.cache-hit != 'true'
-      env:
-        DOCKER_BUILDKIT: '1'
-        COMPOSE_DOCKER_CLI_BUILD: '1'
-    - run: docker tag app/php-image app/php-image-cache && mkdir -p /tmp/docker-save && docker save app/php-image-cache -o /tmp/docker-save/snapshot.tar && ls -lh /tmp/docker-save || true
-      if: always() && steps.docker-php-image-cache.outputs.cache-hit != 'true'
 
     - name: Docker boot
       env:
@@ -44,16 +66,8 @@ jobs:
       timeout-minutes: 4
 
     - name: Sleep
-      run: sleep 10
+      run: sleep 12
     - run: docker-compose ps
-
-    - name: Docker eficode/wait-for MySQL 5.7
-      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:3306 -- echo success
-      timeout-minutes: 1
-
-    - name: Docker eficode/wait-for MySQL 8.0
-      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.3/wait-for | sh -s -- 127.0.0.1:4306 -- echo success
-      timeout-minutes: 1
 
     - name: Cache Composer packages
       id: composer-cache
